name: Crypto Buy Signal Alert

on:
  schedule:
    - cron: "*/5 * * * *"   # 每 5 分鐘（注意：GitHub 使用 UTC 時區）
  workflow_dispatch:       # 手動觸發

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 若你有 requirements.txt，改成：python -m pip install -r requirements.txt
          python -m pip install pandas requests

      - name: Run strategy
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python strategy.py
